# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatabaseConnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 265)
        self.lineHost = QtWidgets.QLineEdit(Form)
        self.lineHost.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.lineHost.setObjectName("lineHost")
        self.lineUser = QtWidgets.QLineEdit(Form)
        self.lineUser.setGeometry(QtCore.QRect(20, 80, 113, 20))
        self.lineUser.setObjectName("lineUser")
        self.linePass = QtWidgets.QLineEdit(Form)
        self.linePass.setGeometry(QtCore.QRect(20, 130, 113, 20))
        self.linePass.setObjectName("linePass")
        self.lineDB = QtWidgets.QLineEdit(Form)
        self.lineDB.setGeometry(QtCore.QRect(20, 180, 113, 20))
        self.lineDB.setObjectName("lineDB")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.ConnectButton = QtWidgets.QPushButton(Form)
        self.ConnectButton.setGeometry(QtCore.QRect(20, 220, 75, 23))
        self.ConnectButton.setObjectName("ConnectButton")
        self.ndicatorDB = QtWidgets.QLabel(Form)
        self.ndicatorDB.setGeometry(QtCore.QRect(170, 110, 171, 16))
        self.ndicatorDB.setObjectName("ndicatorDB")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "host"))
        self.label_2.setText(_translate("Form", "login"))
        self.label_3.setText(_translate("Form", "password"))
        self.label_4.setText(_translate("Form", "name DB"))
        self.ConnectButton.setText(_translate("Form", "CONNECT"))
        self.ndicatorDB.setText(_translate("Form", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
