# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graphic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import test_rc
class Ui_Form(object):
    def graph1(self, Form2):
        Form2.setObjectName("Graphic")
        Form2.resize(760, 422)
        self.label = QtWidgets.QLabel(Form2)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 411))
        self.label.setObjectName("label")
        QtCore.QMetaObject.connectSlotsByName(Form2)
        Form2.setWindowTitle("Form")
        self.label.setText("<html><head/><body><p><img src=\":/newPrefix/2021-12-23_01-42-59.png\"/></p></body></html>")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
